### ISSUE TITLE
NewDownloadTasks progressbar hangs after downloading..?

### ISSUE THREAD

**Issue by xplshn** [hedzr/progressbar#5]
Hi, I'm trying to use this awesome library in my project, but I cannot figure out why the bar hangs after downloading the binaries, it may be an issue with how I am using the library, but there's not much documentation unlike other libraries such as `mpb`, so I thought I'd ask directly if that's fine:
![image](https://github.com/user-attachments/assets/a9b71182-7508-4b2c-8ba1-c54c4166fa30)

I've trying since yesterday but no luck, I've tried all kinds of things and couldn't get it to work correctly, maybe it is a skill issue on my end and not really a problem with this library, in any case, thanks, awesome library even if I'm unable to use it as intended

:)

install.go
```
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hedzr/progressbar"
	"github.com/pkg/xattr"
)

var whichStepper = 1

func installBinaries(ctx context.Context, binaries []string, installDir, trackerFile string, verbosityLevel Verbosity, repositories, metadataURLs []string) error {
	tasks := progressbar.NewDownloadTasks(progressbar.New())
	defer tasks.Close()

	urls, checksums, err := findURL(binaries, trackerFile, repositories, metadataURLs, verbosityLevel)
	if err != nil {
		return err
	}

	var installedBinaries []string
	var errors []string

	for i, binaryName := range binaries {
		url := urls[i]
		checksum := checksums[i]
		destination := filepath.Join(installDir, filepath.Base(binaryName))
		tmpFile := destination + ".tmp"

		if isFileBusy(destination) {
			errors = append(errors, fmt.Sprintf("[%s] is busy and cannot be replaced", destination))
			continue
		}

		tasks.Add(url, tmpFile,
			progressbar.WithBarUpperBound(100),
			progressbar.WithBarStepper(whichStepper),
			progressbar.WithBarOnCompleted(func(bar progressbar.PB) {
				if err := os.Chmod(tmpFile, 0755); err != nil {
					errors = append(errors, fmt.Sprintf("failed to set executable bit for %s: %v", tmpFile, err))
					return
				}

				calculatedChecksum, err := calculateChecksum(tmpFile)
				if err != nil {
					errors = append(errors, fmt.Sprintf("failed to calculate checksum for %s: %v", tmpFile, err))
					return
				}
				if calculatedChecksum != checksum {
					errors = append(errors, fmt.Sprintf("Checksum mismatch for %s: expected %s, got %s", destination, checksum, calculatedChecksum))
					return
				}

				if err := os.Rename(tmpFile, destination); err != nil {
					errors = append(errors, fmt.Sprintf("failed to move %s to %s: %v", tmpFile, destination, err))
					return
				}

				if err := xattr.Set(destination, "user.ManagedBy", []byte("dbin")); err != nil {
					errors = append(errors, fmt.Sprintf("failed to set xattr for %s: %v", destination, err))
					return
				}

				installedBinaries = append(installedBinaries, binaryName)
			}),
		)
	}

	tasks.Wait()

	if len(errors) > 0 {
		finalErr := strings.Join(errors, "\n")
		if verbosityLevel >= silentVerbosityWithErrors {
			return fmt.Errorf(finalErr)
		}
	}

	if trackerFile != "" {
		err := addToTrackerFile(trackerFile, installedBinaries, installDir)
		if err != nil {
			return fmt.Errorf("failed to update tracker file: %v", err)
		}
	}

	return nil
}

func installCommand(binaries []string, installDir, trackerFile string, verbosityLevel Verbosity, repositories, metadataURLs []string) error {
	return installBinaries(context.Background(), removeDuplicates(binaries), installDir, trackerFile, verbosityLevel, repositories, metadataURLs)
}

```

**Comment by hedzr** [comment]
It's really bad to copy this message.

I can't suppose what causes it, but you would like to add more log.Printf before and after the key steps, such as tasks.Wait(). These assertions shall help you for getting more close to the fact.

IMO, though there's no more info, but the most probable reason is that some unexpected branch or exiting condition do make `DownloadTask` not handling these callbacks:

- `func WithTaskAddOnTaskProgressing(cb Worker) TaskOpt`
- `func WithTaskAddOnTaskCompleted(cb OnCompleted) TaskOpt`

The assertions in the two callbacks could be:

```go
progressbar.WithTaskAddOnTaskProgressing(func(bar progressbar.PB, exitCh <-chan struct{}) {
    println(...)
}),
progressbar.WithTaskAddOnTaskProgressing(func(bar progressbar.PB) {
    println(...)
}),
```

If the callbacks are not triggered as we want, you can debug into the codes to locate the final reason.

Lucky.

P.S.,

`NewDownloadTask` might work not very ok if it meets a worse network, since it's a simple wrapper on `http.NewRequest`.
If your code are working on a limited place, rewriting the downloader with curl lib and `progressbar.NewTasks` and catching all of download exceptions and dealing with them, so the `progressbar` will resume the right track.

**Comment by xplshn** [comment]
Thanks for the insight, will update you if I am able to fix it
Awesome library btw

**Comment by xplshn** [comment]
Do you mind adding a multibar example that doesn't use NewDownloadTasks? :)

**Comment by hedzr** [comment]
1. Of course i can, i will do it. But i need a good sample so i can solve it with MultiPB. So, if you have one, introduce it pls, except downlaoding sth from somewhere.
2. Another point is, `Tasks` (task.go) had shown how to use MultiPB, and NewDownloadTasks is an extension on `Tasks`.

**Comment by hedzr** [comment]
Or, downloading sth with Tasks directly?

**Comment by xplshn** [comment]
> Or, downloading sth with Tasks directly?

Yeah, exactly, its not so clear to me, maybe two example with tasks could be added, one that uses a single progressbar and one that uses multiple?

**Comment by hedzr** [comment]
nope. it's a pity i can't write a single pb.

I did some changes on NewDownloadTasks but not commit yet. I'll try making another mpb demo. I'll push all of them later, i guess that will be at tomorrow noon +0800, that is, after 12 hours.

Please take a little bit time to check out the new code and discuss about more clear usage on MultiPB. Thanks.

**Comment by hedzr** [comment]
pushed, bed, and any replies will be reacted at wakeup.
