### ISSUE TITLE
go get will get v1.1.9

### ISSUE THREAD

**Issue by akkuman** [hedzr/progressbar#7]
https://github.com/hedzr/progressbar/commit/a3a45105989ca350d1edbecd69f415d6c6f603c9

I think that should new tag to fix the error

**Comment by hedzr** [comment]
sure, my fault for the oversight, soon

**Comment by hedzr** [comment]
new version at v1.1.11 will be published while ci verified.
this issue was closed because last commit auto triggerred.
any matter could reopen it or create new one freely.

**Comment by akkuman** [comment]
great, thanks for your work
